added version2 lambda updation and publishing code

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -30,40 +30,51 @@ jobs:
           aws lambda get-function --function-name python-lambda1
           echo "existslambda=$?" >> $GITHUB_ENV
 
-      # - name: Create Lambda base function
-      #   if: env.existslambda == '1'  # Runs only if get-function failed (function does NOT exist)
-      #   run: |
-      #     aws lambda create-function \
-      #       --function-name python-lambda1 \
-      #       --runtime python3.9 \
-      #       --zip-file fileb://base.zip \
-      #       --handler lambda_function.handler \
-      #       --role arn:aws:iam::332093714913:role/lambda-canary-execution-role
+      - name: Create Lambda base function
+        if: env.existslambda == '1'  # Runs only if get-function failed (function does NOT exist)
+        run: |
+          aws lambda create-function \
+            --function-name python-lambda1 \
+            --runtime python3.9 \
+            --zip-file fileb://base.zip \
+            --handler lambda_function.handler \
+            --role arn:aws:iam::332093714913:role/lambda-canary-execution-role
 
       - name: Update Lambda base function to version1
         run: |
           aws lambda update-function-code \
             --function-name python-lambda1 \
+            --zip-file fileb://version1.zip
+
+      - name: Check if Lambda version1 exists
+        run: |
+          set +e
+          aws lambda get-function --function-name my-function --qualifier 1
+          echo "existslambdaversion1=$?" >> $GITHUB_ENV
+
+      - name: Create Lambda version v1
+        if: env.existslambdaversion1 == '1'  # Runs only if get-function failed (function does NOT exist)
+        run: |
+          aws lambda publish-version \
+            --function-name python-lambda1 --description "v1"
+
+      - name: Update Lambda base function to version2
+        run: |
+          aws lambda update-function-code \
+            --function-name python-lambda1 \
             --zip-file fileb://version2.zip
 
+      - name: Check if Lambda version2 exists
+        run: |
+          set +e
+          aws lambda get-function --function-name my-function --qualifier 2
+          echo "existslambdaversion2=$?" >> $GITHUB_ENV
 
-      # - name: Check if Lambda version1 exists
-      #   run: |
-      #     set +e
-      #     aws lambda get-function --function-name my-function --qualifier 1
-      #     echo "existslambdaversion=$?" >> $GITHUB_ENV
-
-      # - name: Create Lambda version v1
-      #   if: env.existslambdaversion == '1'  # Runs only if get-function failed (function does NOT exist)
-      #   run: |
-      #     aws lambda publish-version \
-      #       --function-name python-lambda1 --description "v1"
-
-
-
-
-
-
+      - name: Create Lambda version v2
+        if: env.existslambdaversion2 == '1'  # Runs only if get-function failed (function does NOT exist)
+        run: |
+          aws lambda publish-version \
+            --function-name python-lambda1 --description "v2"
 
       # - name: Zip Lambda - v1 code
       #   run: |
